import { Inter } from "next/font/google";
import "../globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import MainHeader from "@/components/layout/MainHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alteride Cabinet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Layout>
            <MainHeader />
            {children}
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
